### ISSUE TITLE
Memory alignment

### ISSUE THREAD

**Issue by carstenbauer** [mkitti/ArrayAllocators.jl#1]
Maybe it's worth adding something like https://github.com/JuliaPerf/BandwidthBenchmark.jl/blob/main/src/allocate.jl to this package. Based on `posix_memalign` this allows one to specify the alignment of objects. Isn't available on Windows though.

See also https://discourse.julialang.org/t/julia-alignas-is-there-a-way-to-specify-the-alignment-of-julia-objects-in-memory/57501/2 where this originated from.

**Comment by mkitti** [comment]
Yes, I should be able to support that. I also have the Windows side figured out which is not that different from the NUMA aware allocation I am doing on Windows now:
https://docs.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-virtualalloc2

**Comment by mkitti** [comment]
I did a rough version in https://github.com/mkitti/ArrayAllocators.jl/commit/b5590a29bc0ee601e4d6b87e3c518ef87008a682 . I should probably switch to pull requests once I actually register and release this package.

**Comment by mkitti** [comment]
Fixed in #3
