### ISSUE TITLE
does this package offer an easier (and safer?) way to manage the memory

### ISSUE THREAD

**Issue by mzy2240** [mkitti/ArrayAllocators.jl#20]
Trying to figure out a way to manually manage the memory of array (mainly the capability to allocate and free memory). I noticed with the help from this package I could do something elegantly like `U = Array{Float64}(malloc, 1024, 1024)` to allocate a memory for array, Im just wondering if it provides any helper functions to manually free the memory as well. Thanks!

**Comment by mkitti** [comment]
This package offers some _alternative_ ways to allocate memory. It uses C allocation functions and then uses [`Base.unsafe_wrap`](https://docs.julialang.org/en/v1/base/c/#Base.unsafe_wrap-Union{Tuple{N},%20Tuple{T},%20Tuple{Union{Type{Array},%20Type{Array{T}},%20Type{Array{T,%20N}}},%20Ptr{T},%20Tuple{Vararg{Int64,%20N}}}}%20where%20{T,%20N}) to wrap the pointer into an `Array`. The `malloc` option is mainly for testing purposes.

Using `calloc` allows for new functionality where you can lazily allocate an array of zeros.

However, this still integrates with the GC. It installs a finalizer which is expected to be called by the garbage collector. If you wanted to eagerly finalize an array, you can [`finalize`](https://docs.julialang.org/en/v1/base/base/#Base.finalize).

If you wanted to manage memory yourself, I would recommend using `unsafe_wrap` directly. The following example uses `Base` Julia only.

```julia
# Manually allocate memory
ptr = Libc.malloc(1024)
A = unsafe_wrap(Array{UInt8}, Ptr{UInt8}(ptr), 32, 32; own = false)
sum(A)

# Manually free the memory
A = nothing
Libc.free(ptr)
```

You may also want to consider a package like https://github.com/MasonProtter/Bumper.jl

**Comment by mzy2240** [comment]
thank you for the detailed explanation, I sincerely appreciate it! one quick question regarding the example, if `unsafe_wrap` the manually allocated memory with `own=false`, is it taking the risk that other programs may write to the same memory during the lifecycle?

**Comment by mkitti** [comment]
No. `own = false` means that Julia will not try to free the memory. It means that you are responsible for freeing the memory.

It would be better to discuss this at https://discourse.julialang.org/
